name: MysteryCrate
main: JackMD\MysteryCrate\Main
api: [1.1.3, 2.0.0, 2.0.1, 3.0.0, 3.0.1, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0-ALPHA13, 3.0.0-ALPHA14, 3.0.0-ALPHA15]
version: 6.0.0
author: JackMD
authors: [DaPigGuy]
load: POSTWORLD
description: Plugin này giúp thêm MysteryCrate vào server của bạn với tùy chỉnh enchants.
website: https://github.com/JackMD/MysteryCrate
translator: GamerSoiCon

permissions:
 mc.crates.use:
  default: true
  description: "Cho phép sử dụng crates."
 mc.command.key:
  default: op
  description: "Cho phép sử dụng lệnh /key"
 mc.crates.create:
  default: op
  description: "Cho phép tạo ra crates."
 mc.crates.destroy:
  default: op
  description: "Cho phép đập crates (giống như hủy bỏ crates ấy)."
