---
name: MysteryCrate
main: JackMD\MysteryCrate\Main
api:
- 3.9.0
version: 9.2.0
author: JackMD
translator: WolfTubeTM
authors:
- DaPigGuy
load: POSTWORLD
description: Thùng quay thưởng không giới hạn với đầy đủ tùy chỉnh.
website: https://github.com/JackMD/MysteryCrate
permissions:
  mc.crates.use:
    default: true
    description: Cho phép sử dụng thùng.
  mc.command.key:
    default: op
    description: Cho phép sử dụng lệnh /key
  mc.command.keyall:
    default: op
    description: Cho phép sử dụng lệnh /keyall
  mc.crates.create:
    default: op
    description: Cho phép tạo thùng.
  mc.crates.destroy:
    default: op
    description: Cho phép phá hủy thùng.
...
