#  ___  ___          _                  _____           _
#  |  \/  |         | |                /  __ \         | |
#  | .  . |_   _ ___| |_ ___ _ __ _   _| /  \/_ __ __ _| |_ ___
#  | |\/| | | | / __| __/ _ \ '__| | | | |   | '__/ _` | __/ _ \
#  | |  | | |_| \__ \ ||  __/ |  | |_| | \__/\ | | (_| | ||  __/
#  \_|  |_/\__, |___/\__\___|_|   \__, |\____/_|  \__,_|\__\___|
#           __/ |                  __/ |
#          |___/                  |___/  Bởi @JackMD cho PMMP
#                                              
#
# MysteryCrate, là một plugin Crate cho PocketMine-MP
# Bản Quyền (c) 2018 JackMD  < https://github.com/JackMD >
#
# Discord: JackMD#3717
# Twitter: JackMTaylor_
#
# Phần mềm này được phân phối theo "Giấy phép Công cộng GNU v3.0".
# Giấy phép này cho phép bạn sử dụng hoặc sửa đổi nó nhưng bạn không
# được phép bán plugin này bằng mọi giá. Nếu làm như vậy, chúng tôi
# sẽ thực hiện một hành động cần thiết.
#
# MysteryCrate được phân phối với hy vọng rằng nó sẽ hữu ích,
# nhưng KHÔNG CÓ BẤT KÌ BẢO HÀNH; thậm chí không có bảo hành ngụ ý
# TRÁCH NHIỆM hoặc PHÙ HỢP CHO MỘT MỤC ĐÍCH CỤ THỂ. Xem
# GNU General Public License v3.0 để biết thêm chi tiết.
#
# Bạn đã nhận được một bản sao của Giấy phép Công cộng GNU v3.0
# cùng với chương trình này. Nếu không, hãy xem
# <https://opensource.org/licenses/GPL-3.0>.
#
# PLUGIN ĐƯỢC DỊCH RA TIẾNG VIỆT BỞI SÓI
# BẢN QUYỀN PLUGIN THUỘC VỀ JACKMD
#  -----------------------------------------------------------------------

# Bạn có thể chỉnh sửa ID:Meta của key để mở Crates ở dưới đây !
# (Tips) Nhưng tôi khuyên bạn không nên chỉnh trừ khi bạn biết sửa đổi mã nguồn !!
key: "339:0"

# Chỉnh sửa mô tả cho Key
# Khi cầm Key trên tay, nó sẽ hiển thị những mô tả này. Khá là hữu ích phải không nào ?
descOne: "Sử dụng Key tại /warp crates."
descTwo: "Bạn có cơ hội nhận được Công Cụ OP đấy !!!"

# Hãy nhập tên Thế giới (world) mà bạn muốn đặt Crate nào !
# (Tips) Ví dụ thư mục của bạn là world nhưng tên thế giới của bạn là lobby thì bạn hãy nhập "lobby" vào crateWorld nhé !
crateWorld: "Master"

# Đặt giá trị bạn muốn lệnh được nhận diện. Hãy chắc chắn rằng nó ở giữa 10-50
# Nếu bạn muốn thưởng cho người chơi bằng một lệnh, hãy đặt meta của phần thưởng trong crates.yml 
# đến giá trị bạn đặt trong commandMeta.
# (phần này mình cũng không biết dịch sao cho đúng nữa -_- nhưng mà, theo mình nghĩ thì cái commandMeta này là Custom Item)
commandMeta: 50

# Nhập thời gian bạn muốn Crate chạy vào đây. Tăng giá trị này sẽ tăng
# thời gian người chơi nhận được phần thưởng và ngược lại.
# Tôi khuyến nghị bạn nên để nguyên 2
# Giá trị được đặt là đơn vị giây !
tickDelay: 2

# Nếu như server bạn khá lag và đông người thì tôi khuyên bạn nên để false.
# Điều này sẽ tắt hiệu ứng khi quay Crate, nếu bạn muốn bật lại, hãy để true ở showParticle
showParticle: true
